sm - Copy/config/routes.rb
Rails.application.routes.draw do
  get 'register' => "registers#new"
  get 'registers/create'
  get 'registers/destroy'

  get 'login' => "sessions#new", :as => "login"
  get 'sessions/create'
  get 'logout' => "sessions#destroy", :as => "logout"
  namespace :admin do
    get 'results/new'
    get 'results/create'
    get 'results/edit'
    get 'results/update'
    get 'results/destroy'
    get 'results/index'
    get 'results/show'
  end
  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
    get 'users/index'
    get 'users/show'
  end
  namespace :admin do
    get 'departments/new'
    get 'departments/create'
    get 'departments/edit'
    get 'departments/update'
    get 'departments/destroy'
    get 'departments/index'
    get 'departments/show'
  end
  namespace :admin do
    get 'courses/new'
    get 'courses/create'
    get 'courses/edit'
    get 'courses/update'
    get 'courses/destroy'
    get 'courses/index'
    get 'courses/show'
  end
  namespace :admin do
    get 'students/new'
    get 'students/create' 
    get 'students/edit'
    get 'students/update'
    get 'students/destroy'
    get 'students/index'
    get 'students/show'
  end
  get 'courses/index'
  get 'courses/show'
  get 'results/index'
  get 'results/show'
  get 'students/new'
  get 'students/create'
  get 'students/edit'
  get 'students/update'
  get 'students/destroy'
  get 'students/index'
  get 'students/show'

  resources :students, :results, :courses
  namespace :admin do
    resources :students, :results, :courses, :users, :departments
  end
   root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sm - Copy/app/models/result.rb
class Result < ApplicationRecord

    belongs_to :student
	belongs_to :department
	belongs_to :course

	validates :student_id, presence: true
	validates :department_id, presence: true
	validates :course_id, presence: true
	validates :marks, presence: true
	validates :level, presence: true


	def self.search(query)
		where("student.reg_number like ? ", "%#{query}")
	end
    
end

sm - Copy/app/controllers/admin/results_controller.rb
class Admin::ResultsController < Admin::ApplicationController
  def new
    @page_title = 'Add New Marks'
    @result = Result.new
  end

  def create
    @result = Result.new(result_params)
    if @result.save
      flash[:notice] = 'Marks added!'
      redirect_to admin_results_path
    else
      render 'new'
    end
  end

  def edit
    @page_title = 'Edit Marks'
    @result = Result.find(params[:id])

  end

  def update
     @result = Result.find(params[:id])
   if  @result.update(result_params)
      flash[:notice] = 'Marks updated!'
       redirect_to admin_results_path
     else
      render 'edit'
    end
  end

  def destroy
     @result = Result.find(params[:id])
    @result.destroy
    flash[:notice] = 'Marks deleted!'

    redirect_to admin_results_path
  end

  def index 
    @page_title = 'Marks'
    @results = Result.all
    @student = Student.all
    @department = Department.all
  end

  def show
    if params[:search]
      @result = Result.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @results = Result.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
    @page_title = 'Marks for:'
    @result = Result.find(params[:id])
    @department = Department.all
    @student = Student.all

    respond_to do |format|
      format.html
      format.pdf do
        pdf = ResultPdf.new(@result)
        send_data pdf.render, filename: 'marks for: '+(@result.student.reg_number)+'.pdf', type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  def result_params
    params.require(:result).permit(:student_id, :course_id, :user_id, :department_id, :level, :marks)
  end 
end

sm - Copy/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @page_title = 'Marks'
    @results = Result.all
    @student = Student.all
    @department = Department.all
  end

  def show
    @page_title = 'Marks for:'
    @result = Result.find(params[:department_id] && params[:level] && params[:ac_year])
    @department = Department.all
    @student = Student.all
  end
end

sm - Copy/app/helpers/admin/results_helper.rb
module Admin::ResultsHelper
end

sm - Copy/app/helpers/results_helper.rb
module ResultsHelper
end

sm - Copy/app/views/admin/results/create.html.erb
<h1>Admin::Results#create</h1>
<p>Find me in app/views/admin/results/create.html.erb</p>

sm - Copy/app/views/admin/results/destroy.html.erb
<h1>Admin::Results#destroy</h1>
<p>Find me in app/views/admin/results/destroy.html.erb</p>

sm - Copy/app/views/admin/results/edit.html.erb
<h2><%= @page_title%></h2>
<%= form_for [:admin, @result] do |f| %>

<% if @result.errors.any? %>
  <% @result.errors.full_messages.each do |msg| %>
   <!-- show errors -->
     <div class="alert alert-danger"><%= msg %></div>
     <% end %>
  <% end %>
	<div class="form-group">
		<%= f.label :registration_number%><br/>
		<%= f.select :student_id, Student.all.collect {|x|[x.reg_number, x.id]}, {:include_blank => 'pick registration number'}, class:'form-control'%>
	</div>
	<div class="form-group">
		<%= f.label :academic_year %><br/>
		<%=f.text_field :ac_year, placeholder:'2017-2018', class:'form-control'%>
	</div>
		<div class="form-group">
		<%= f.label :module%><br/>
		<%= f.select :course_id, Course.all.collect {|x|[x.module_name, x.id]}, {:include_blank => 'select one'}, class:'form-control'%>
	</div>		
	<div class="form-group">
		<%= f.label :department%><br/>
		<%= f.select :department_id, Department.all.collect {|x|[x.name, x.id]}, {:include_blank => 'select one'}, class:'form-control'%>
	</div>
	<div class="form-group">
		<%= f.label :level%><br/>
		<%= f.select :level, options_for_select([[1],[2],[3],[4]]), {:include_blank => 'select one'},class:'form-control'%>
	</div>
		<div class="form-group">
		<%= f.label :marks%><br/>
		<%=f.text_field :marks, class:'form-control'%>
		</div>
	<%= f.submit 'Submit',class:'btn btn-primary' %>
		<%= link_to 'Cancel', admin_results_path, class:'btn btn-default'%>
<% end %>

sm - Copy/app/views/admin/results/index.html.erb
<h2><%= @page_title%></h2>
<%= link_to  "Add new", new_admin_result_path, class:'btn btn-success pull-right' %>

<table class="table table-striped">
  <tr> 
    <th>Department</th>
    <th>Level</th>
    <th>Academic</th>
    <th>Action</th>
  </tr>
  <% @results.each do |result|%>
  <tr>
    <td><%= result.department.name %></td>
    <td><%= result.level %></td>
    <td><%= result.ac_year %></td>
    <td><%= link_to  "View result", admin_result_path(result), class:'btn btn-primary' %></td>
  </tr>
  <% end %>
  </table>

sm - Copy/app/views/admin/results/new.html.erb
<h2><%= @page_title%></h2>
<%= form_for [:admin, @result] do |f| %>

<% if @result.errors.any? %>
  <% @result.errors.full_messages.each do |msg| %>
   <!-- show errors -->
     <div class="alert alert-danger"><%= msg %></div>
     <% end %>
  <% end %>
	<div class="form-group">
		<%= f.label :registration_number%><br/>
		<%= f.select :student_id, Student.all.collect {|x|[x.reg_number, x.id]}, {:include_blank => 'pick registration number'}, class:'form-control'%>
	</div>
	<div class="form-group">
		<%= f.label :registration_year %><br/>
		<%=f.select :ac_year, Student.all.collect {|x| [x.ac_year, x.id]}, placeholder:'2017-2018', class:'form-control'%>
	</div>
	<div class="form-group">
		<%= f.label :department%><br/>
		<%= f.select :department_id, Department.all.collect {|x|[x.name, x.id]}, {:include_blank => 'select one'}, class:'form-control'%>
	</div>
	<div class="form-group">
		<%= f.label :module%><br/>
		<%= f.select :course_id, Course.all.collect {|x|[x.module_name, x.id]}, {:include_blank => 'select one'}, class:'form-control'%>
	</div>		
	<div class="form-group">
		<%= f.label :level%><br/>
		<%= f.select :level, options_for_select([[1],[2],[3],[4]]), {:include_blank => 'select one'},class:'form-control'%>
	</div>
		<div class="form-group">
		<%= f.label :marks%><br/>
		<%=f.text_field :marks, class:'form-control'%>
		</div>
	<%= f.submit 'Submit',class:'btn btn-primary' %>
		<%= link_to 'Cancel', admin_results_path, class:'btn btn-default'%>
<% end %>

sm - Copy/app/views/admin/results/show.html.erb
<h2><%= @page_title%> <small> Year <%= @result.level %> <%= @result.department.name %></small></h2>
<% if @results.exists? %>
<div class="row">
      <div class="col-md-6 col-sm-6">
	  <%= link_to 'Save(PDF)', result_path(@result, format: 'pdf'), class:'btn btn-primary' %>
        </div>
        <div class="col-md-6 col-sm-6">
         <%= render  "partials/admin/search", class:'pull-right'%>
        </div>
      </div>
	<table class="table table-striped">
		<tr>
			<th>Registration Number</th>
			<th>Module Code</th>
			<th>Marks</th>
			<th>Year Registered</th>
			<th>Department</th>
			<th>Level</th>
			<th>Action</th>
		</tr>
		<tr>
			<td><%= @result.student.reg_number %></td>
			<td><%= @result.course.module_code %></td>
			<td><%= @result.marks %></td>
			<td><%= @result.ac_year %></td>
			<td><%= @result.department.name %></td>
			<td><%= @result.level %></td>
			<td><%= link_to 'Edit', edit_admin_result_path(@result.id),class:'btn btn-primary'%> <%= link_to 'Delete', results_path, method: :delete, data: {confirm: 'Are you sure?'}, class:'btn btn-danger'%></td>
		</tr>
	</table>
	<%= will_paginate @resulst%>
<% else %>
  <p><h3>No resutls available now</h3></p>
<% end %>
  

sm - Copy/app/views/admin/results/update.html.erb
<h1>Admin::Results#update</h1>
<p>Find me in app/views/admin/results/update.html.erb</p>