sm - Copy/config/routes.rb
Rails.application.routes.draw do
  get 'register' => "registers#new"
  get 'registers/create'
  get 'registers/destroy'

  get 'login' => "sessions#new", :as => "login"
  get 'sessions/create'
  get 'logout' => "sessions#destroy", :as => "logout"
  namespace :admin do
    get 'results/new'
    get 'results/create'
    get 'results/edit'
    get 'results/update'
    get 'results/destroy'
    get 'results/index'
    get 'results/show'
  end
  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
    get 'users/index'
    get 'users/show'
  end
  namespace :admin do
    get 'departments/new'
    get 'departments/create'
    get 'departments/edit'
    get 'departments/update'
    get 'departments/destroy'
    get 'departments/index'
    get 'departments/show'
  end
  namespace :admin do
    get 'courses/new'
    get 'courses/create'
    get 'courses/edit'
    get 'courses/update'
    get 'courses/destroy'
    get 'courses/index'
    get 'courses/show'
  end
  namespace :admin do
    get 'students/new'
    get 'students/create' 
    get 'students/edit'
    get 'students/update'
    get 'students/destroy'
    get 'students/index'
    get 'students/show'
  end
  get 'courses/index'
  get 'courses/show'
  get 'results/index'
  get 'results/show'
  get 'students/new'
  get 'students/create'
  get 'students/edit'
  get 'students/update'
  get 'students/destroy'
  get 'students/index'
  get 'students/show'

  resources :students, :results, :courses
  namespace :admin do
    resources :students, :results, :courses, :users, :departments
  end
   root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sm - Copy/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sm - Copy/app/models/course.rb
class Course < ApplicationRecord
    belongs_to :department
    belongs_to :user
end

sm - Copy/app/models/department.rb
class Department < ApplicationRecord
    has_many :students
	has_many :modules
    has_many :results
    
    validates :name, presence: true
    validates :full_name, presence: true
end

sm - Copy/app/models/result.rb
class Result < ApplicationRecord

    belongs_to :student
	belongs_to :department
	belongs_to :course

	validates :student_id, presence: true
	validates :department_id, presence: true
	validates :course_id, presence: true
	validates :marks, presence: true
	validates :level, presence: true


	def self.search(query)
		where("student.reg_number like ? ", "%#{query}")
	end
    
end

sm - Copy/app/models/result_pdf.rb
lass ResultPdf < Prawn::Document
	def initialize(result)
		super(top_margin:70)
		@result = Result.all
		reg_number
		#text 'Marks for: '+result.student.reg_number
		line_marks
		
	end
	def reg_number
		#text "Marks for: #{result.student.reg_number}"

	end
	def line_marks
		move_down 20
		table line_marks_rows do 
			row(0).font_style= :bold
		end
	end
	def line_marks_rows
		[['Registration Number','Module Code', 'Level', 'Department', 'Marks']]+
		@result.map do |result|
			[result.student.reg_number, result.course.module_code, result.level, result.department.name, result.marks]
		end
	end

end 

sm - Copy/app/models/student.rb
class Student < ApplicationRecord
    belongs_to :department

    validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	validates :password, presence: true

   
end

sm - Copy/app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    before_save :encrypt_password
    belongs_to :department

    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true
    validates :password, confirmation: true

    def self.authenticate(email, password)
        user = find_by_email(email)
        if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
            user
        else
            nil
        end
    end
        def encrypt_password
            if password.present?
                self.password_salt = BCrypt::Engine.generate_salt
                self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
            end 
        end
end

sm - Copy/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def new
    @page_title = 'Add New User'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User created'
      redirect_to admin_users_path
    else
      render 'new'
    end 
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'User updated'
      redirect_to admin_users_path
    else
      render 'edit'
    end 
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'User removed'
    redirect_to admin_users_path
  end
  def index
    @page_title = 'Manage users'
    @department = Department.all
    @users = User.all
  end

  def show
  end
  def user_params
    params.require(:user).permit(:name, :email, :department_id, :phone, :position, :password)
  end
end

sm - Copy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

sm - Copy/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  end

  def show
  end
end

sm - Copy/app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  layout 'login'
  def new
    @page_title = 'Student Register'
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = 'Student added!'
      redirect_to login_path
    else
      render 'register'
      flash[:alert] = 'Enable to register'
    end
  end

  def destroy
  end
  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :password)
  end
end

sm - Copy/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @page_title = 'Marks'
    @results = Result.all
    @student = Student.all
    @department = Department.all
  end

  def show
    @page_title = 'Marks for:'
    @result = Result.find(params[:department_id] && params[:level] && params[:ac_year])
    @department = Department.all
    @student = Student.all
  end
end

sm - Copy/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'login'
  def new
    @page_title = 'Login'
  end

  def create
  end

  def destroy
  end
end

sm - Copy/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def new
    @page_title = 'Add New Student'
    @student = Student.new

  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = 'Student added!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @page_title = 'Edit Student'
    @student = Student.find(params[:id])

  end

  def update
     @student = Student.find(params[:id])
   if  @student.update(student_params)
      flash[:notice] = 'Student updated!'
       redirect_to root_path
     else
      render 'edit'
    end
  end

  def destroy
     @student = Student.find(params[:id])
    @student.destroy
    flash[:notice] = 'Student deleted!'

    redirect_to departments_path
  end

  def index
    @page_title = 'Students'
    @students = Student.all
    @department = Department.all
  end

  def show
    @page_title = 'Student Info'
    @student = Student.find(params[:id])
    @department = Department.all
  end
  def student_params
    params.require(:student).permit(:first_name, :last_name, :sex, :address, :guardian_name, :nid_passport, :department_id, :level, :reg_number, :ubudehe, :nationality, :sponsor, :password, :dob, :email, :telephone, :father_name, :mother_name, :profile_picture)
  end
end

sm - Copy/app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

sm - Copy/app/helpers/admin/results_helper.rb
module Admin::ResultsHelper
end

sm - Copy/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

sm - Copy/app/helpers/application_helper.rb
module ApplicationHelper
end

sm - Copy/app/helpers/courses_helper.rb
module CoursesHelper
end

sm - Copy/app/helpers/registers_helper.rb
module RegistersHelper
end

sm - Copy/app/helpers/results_helper.rb
module ResultsHelper
end

sm - Copy/app/helpers/sessions_helper.rb
module SessionsHelper
end

sm - Copy/app/helpers/students_helper.rb
module StudentsHelper
end

sm - Copy/app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

sm - Copy/app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

sm - Copy/app/views/admin/users/edit.html.erb
<h2><%= @page_title %> </h2>
<%= form_for [:admin, @user] do |f| %>
    <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |msg| %>
           <div class="alert alert-danger"><%= msg %></div>
        <% end %>
        
    <% end %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :position %>
        <%= f.text_field :position, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :telephone %>
        <%= f.text_field :phone, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :department %>
        <%= f.select :department_id, Department.all.collect {|x|[x.name, x.id]}, {:include_blank => 'select one'}, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class:'form-control' %>
    </div>
    <%= f.submit "Submit", class:'btn btn-primary' %>
    <%= link_to  "Cancel", admin_users_path, class:'btn btn-default' %>
<% end %>

sm - Copy/app/views/admin/users/index.html.erb
<h2 class="page-header"><%= @page_title %></h2>
<%= link_to 'Add New User', new_admin_user_path, class:'btn btn-success pull-right'%>
<% if @users.exists? %>
<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Department</th>
        <th>Telephone</th>
        <th>Position</th>
        <th>Created Date</th>
        <th>Action</th>
    </tr>
    <% @users.each do |user| %>
        <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.department.name %></td>
            <td><%= user.phone %></td>
            <td><%= user.position %></td>
            <td><%= user.created_at.to_time.strftime('%B %e at %l : %M %p') %></td>
            <td><%= link_to 'Edit', edit_admin_user_path(user), class:'btn btn-primary'%> <%= link_to 'Delete', admin_user_path(user), class:'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
</table>
<% else %>
 <p>There are no user</p>
<% end %>

sm - Copy/app/views/admin/users/new.html.erb
<h2><%= @page_title %> </h2>
<%= form_for [:admin, @user] do |f| %>
    <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |msg| %>
           <div class="alert alert-danger"><%= msg %></div>
        <% end %>
        
    <% end %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :position %>
        <%= f.text_field :position, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :telephone %>
        <%= f.text_field :phone, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :department %>
        <%= f.select :department_id, Department.all.collect {|x|[x.name, x.id]}, {:include_blank => 'select one'}, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class:'form-control' %>
    </div>
    <%= f.submit "Submit", class:'btn btn-primary' %>
    <%= link_to  "Cancel", admin_users_path, class:'btn btn-default' %>
<% end %>

sm - Copy/app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>

sm - Copy/app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>