sm/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'login' => "sessions#new", :as => "login"
    get 'sessions/create'
    get 'logout' => "sessions#destroy", :as => "logout"
  end
  get 'registers/new' 
  get 'registers/create'
  get 'registers/destroy'

  get 'login' => "sessions#new", :as => "login"
  get 'sessions/create'
  get 'logout' => "sessions#destroy", :as => "logout"
  namespace :admin do
    get 'results/new'
    get 'results/create'
    get 'results/edit'
    get 'results/update'
    get 'results/destroy'
    get 'results/index'
    get 'results/show'
  end
  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
    get 'users/index'
    get 'users/show'
  end
  namespace :admin do
    get 'departments/new'
    get 'departments/create'
    get 'departments/edit'
    get 'departments/update'
    get 'departments/destroy'
    get 'departments/index'
    get 'departments/show'
  end
  namespace :admin do
    get 'courses/new'
    get 'courses/create'
    get 'courses/edit'
    get 'courses/update'
    get 'courses/destroy'
    get 'courses/index'
    get 'courses/show'
  end
  namespace :admin do
    get 'students/new'
    get 'students/create' 
    get 'students/edit'
    get 'students/update'
    get 'students/destroy'
    get 'students/index'
    get 'students/show'
  end
  get 'courses/index'
  get 'courses/show'
  get 'results/index'
  get 'results/show'
  get 'students/new'
  get 'students/create'
  get 'students/edit'
  get 'students/update'
  get 'students/destroy'
  get 'students/index'
  get 'students/show'

  resources :students, :results, :courses, :registers
  namespace :admin do
    resources :students, :results, :courses, :users, :departments, :sessions
  end
   root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sm/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sm/app/models/course.rb
class Course < ApplicationRecord
    belongs_to :department
    belongs_to :user
end

sm/app/models/department.rb
class Department < ApplicationRecord
    has_many :students
	has_many :modules
    has_many :results
    
    validates :name, presence: true
    validates :full_name, presence: true
end

sm/app/models/result.rb
class Result < ApplicationRecord

    belongs_to :student
	belongs_to :department
	belongs_to :course

	validates :student_id, presence: true
	validates :department_id, presence: true
	validates :course_id, presence: true
	validates :marks, presence: true
	validates :level, presence: true


	def self.search(query)
		where("student.reg_number like ? ", "%#{query}")
	end
    
end

sm/app/models/result_pdf.rb
lass ResultPdf < Prawn::Document
	def initialize(result)
		super(top_margin:70)
		@result = Result.all
		reg_number
		#text 'Marks for: '+result.student.reg_number
		line_marks
		
	end
	def reg_number
		#text "Marks for: #{result.student.reg_number}"

	end
	def line_marks
		move_down 20
		table line_marks_rows do 
			row(0).font_style= :bold
		end
	end
	def line_marks_rows
		[['Registration Number','Module Code', 'Level', 'Department', 'Marks']]+
		@result.map do |result|
			[result.student.reg_number, result.course.module_code, result.level, result.department.name, result.marks]
		end
	end

end 

sm/app/models/student.rb
class Student < ApplicationRecord
    belongs_to :department

    validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	validates :password, presence: true

   
end

sm/app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    before_save :encrypt_password
    belongs_to :department

    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true
    validates :password, confirmation: true

    def self.authenticate(email, password)
        user = find_by_email(email)
        if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
            user
        else
            nil
        end
    end
        def encrypt_password
            if password.present?
                self.password_salt = BCrypt::Engine.generate_salt
                self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
            end 
        end
end

sm/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

sm/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  end

  def show
  end
end

sm/app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  layout 'login'
  def new
    @page_title = 'Student Register'
    @student = Student.new
    @department = Department.all
  end

  def create
    @department = Department.all
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = 'registered successfully'
      redirect_to login_path
    else
      render 'new'
    end
  end

  def destroy
  end
  def student_params
    params.permit(:first_name, :last_name, :email, :password)
  end
end

sm/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @page_title = 'Marks'
    @results = Result.all
    @student = Student.all
    @department = Department.all
  end

  def show
    @page_title = 'Marks for:'
    @result = Result.find(params[:department_id] && params[:level] && params[:ac_year])
    @department = Department.all
    @student = Student.all
  end
end

sm/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'login'
  def new
    @page_title = 'Login'
  end

  def create
  end

  def destroy
  end
end

sm/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def new
    @page_title = 'Add New Student'
    @student = Student.new

  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = 'Student added!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @page_title = 'Edit Student'
    @student = Student.find(params[:id])

  end

  def update
     @student = Student.find(params[:id])
   if  @student.update(student_params)
      flash[:notice] = 'Student updated!'
       redirect_to root_path
     else
      render 'edit'
    end
  end

  def destroy
     @student = Student.find(params[:id])
    @student.destroy
    flash[:notice] = 'Student deleted!'

    redirect_to departments_path
  end

  def index
    @page_title = 'Students'
    @students = Student.all
    @department = Department.all
  end

  def show
    @page_title = 'Student Info'
    @student = Student.find(params[:id])
    @department = Department.all
  end
  def student_params
    params.require(:student).permit(:first_name, :last_name, :sex, :address, :guardian_name, :nid_passport, :department_id, :level, :reg_number, :ubudehe, :nationality, :sponsor, :password, :dob, :email, :telephone, :father_name, :mother_name, :profile_picture)
  end
end

sm/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

sm/app/helpers/application_helper.rb
module ApplicationHelper
end

sm/app/helpers/courses_helper.rb
module CoursesHelper
end

sm/app/helpers/registers_helper.rb
module RegistersHelper
end

sm/app/helpers/results_helper.rb
module ResultsHelper
end

sm/app/helpers/sessions_helper.rb
module SessionsHelper
end

sm/app/helpers/students_helper.rb
module StudentsHelper
end

sm/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title ? @page_title : 'Welcome'%> | SMMIS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-default">
      <a class="navbar-brand disabled" href="#"></a>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= params[:controller] == 'students' ? 'active' : '' %>">
            <%= link_to 'Home', root_path, class:'nav-link' %>
          </li>
          <li class="nav-item <%= params[:controller] == 'results' ? 'active' : '' %>">
           <%= link_to 'Results', results_path, class:'nav-link' %>
          </li>
          <li class="nav-item <%= params[:controller] == 'courses'? 'active' : '' %>">
            <%= link_to 'Modules', courses_path, class:'nav-link' %>
           </li>
          <li class="nav-item <%= params[:controller] == 'admin'? 'active' : '' %>">
            <%= link_to 'Admin', admin_login_path, class:'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
    	<% if flash[:notice] %>
    	<div class="alert alert-info"><%= flash[:notice] %></div>
    	<% end %>
    	 <%= yield %>
    </div>
  </body>
</html>

sm/app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %> | SoICT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'login.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
       
       <div class="row">
        <div class="col-md-6">
          <!-- UR Logo -->
          </br>
          </br>
          </br>
          <%= image_tag  "ur.PNG" %>
          </br>
          </br>
          <p class="h4 mb-4"><%= @page_title %></p>
        </div>
        <div class="col-md-6">
            <% if flash[:notice] %>
            <div class="alert alert-info"><%= flash[:notice] %></div>
            <% end %>

            <%= yield %>
         </div>
    </div>

  </body>
</html>